import React from 'react';
import { X, Book, Terminal, Zap, ShieldCheck, GitPullRequest, Code2, Cpu } from 'lucide-react';

const DocsModal = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  const DOCS_SECTIONS = [
    {
      title: 'Core Architecture',
      icon: <Cpu size={18} className="text-cyan-400" />,
      content: 'DevAgent uses OpenAI GPT-4o to analyze code ASTs and runtime behavior. It maintains a stateful understanding of your repository structure to provide high-precision fixes.'
    },
    {
      title: 'Autonomous Workflow',
      icon: <Terminal size={18} className="text-purple-400" />,
      content: 'The agent loop follows: Scan → Detect → Reason → Patch → Verify. Each step is logged in the Pipeline panel for full transparency of the AI decision process.'
    },
    {
      title: 'GitHub Integration',
      icon: <GitPullRequest size={18} className="text-emerald-400" />,
      content: 'Connect your GitHub account to allow the agent to clone repositories, create branches, and push verified pull requests directly to your upstream.'
    },
    {
      title: 'Safety & Verification',
      icon: <ShieldCheck size={18} className="text-orange-400" />,
      content: 'Every fix generated by the agent is automatically validated against your project\'s test suite. If tests fail, the agent analyzes the failure and iterates on the patch.'
    }
  ];

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 md:p-10 animate-fade-in">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-black/80 backdrop-blur-xl transition-all duration-500"
        onClick={onClose}
      />

      {/* Floating Rectangle Box */}
      <div className="relative w-full max-w-4xl bg-[#0B0F19] rounded-[2rem] border border-white/10 shadow-[0_0_100px_rgba(34,211,238,0.15)] overflow-hidden flex flex-col max-h-[85vh] animate-fade-up">
        
        {/* Header */}
        <div className="flex items-center justify-between px-8 py-6 border-b border-white/5 bg-white/[0.02]">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-2xl bg-cyan-500/10 border border-cyan-500/20 flex items-center justify-center">
              <Book size={20} className="text-cyan-400" />
            </div>
            <div>
              <h2 className="text-lg font-black text-white">Documentation</h2>
              <p className="text-[10px] text-gray-500 font-bold uppercase tracking-widest">Master the agentic workflow</p>
            </div>
          </div>
          <button 
            onClick={onClose}
            className="p-2 rounded-xl hover:bg-white/10 text-gray-500 hover:text-white transition-all group"
          >
            <X size={20} className="group-hover:rotate-90 transition-transform duration-300" />
          </button>
        </div>

        {/* Content Area */}
        <div className="flex-1 overflow-y-auto p-8 custom-scrollbar">
          <div className="grid md:grid-cols-2 gap-6">
            {DOCS_SECTIONS.map((section, i) => (
              <div 
                key={i}
                className="p-6 rounded-3xl bg-white/[0.02] border border-white/5 hover:border-cyan-500/30 hover:bg-cyan-500/5 transition-all duration-300 group"
              >
                <div className="flex items-center gap-3 mb-4">
                  <div className="p-2.5 rounded-xl bg-white/5 border border-white/10 group-hover:scale-110 transition-transform duration-500">
                    {section.icon}
                  </div>
                  <h3 className="font-bold text-white text-base">{section.title}</h3>
                </div>
                <p className="text-sm text-gray-400 leading-relaxed font-medium">
                  {section.content}
                </p>
              </div>
            ))}
          </div>

        </div>

        {/* Footer */}
        <div className="px-8 py-6 border-t border-white/5 bg-white/[0.02] flex items-center justify-between">
          <div className="text-[10px] text-gray-500 font-bold uppercase tracking-widest">
            Last Updated: May 2024
          </div>
          <button 
            onClick={onClose}
            className="px-6 py-2 rounded-full bg-vscode-accent text-white text-xs font-black uppercase tracking-widest hover:opacity-90 transition-all shadow-glow-blue active:scale-95"
          >
            Got it, thanks!
          </button>
        </div>

        {/* Decorative Accent */}
        <div className="h-1 w-full bg-gradient-to-r from-cyan-500 via-blue-500 to-purple-500 opacity-60" />
      </div>
    </div>
  );
};

export default DocsModal;
